name: cloid_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^1.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Earthbound
      fonts:
        - asset: assets/fonts/earthbound-regular.otf
        - asset: assets/fonts/earthbound-condensed-bold.otf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_image.svg
  fullscreen: true
  android: true
  ios: false
  web: false

  android_12:
    image: assets/images/splash_android12.png
    icon_background_color: "#ffffff"
